import { Product } from "./schema";

export const localProducts: Product[] = [
  {
    _id: "1",
    productName: "iPhone 15 Pro Max",
    slug: "iphone-15-pro-max",
    productImage: ["/image/products/product_1.jpg"],
    description: "The latest iPhone with advanced camera system and powerful A17 Pro chip.",
    price: 1199,
    discount: 10,
    category: ["mobile", "smartphone", "gadget"],
    stock: 25,
    brand: "Apple",
    rating: 4.8,
    status: "new",
    variant: "gadget",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "2",
    productName: "Samsung Galaxy S24 Ultra",
    slug: "samsung-galaxy-s24-ultra",
    productImage: ["/image/products/product_2.jpg"],
    description: "Flagship Android smartphone with 200MP camera and Snapdragon 8 Gen 3.",
    price: 1299,
    discount: 15,
    category: ["mobile", "smartphone", "gadget"],
    stock: 30,
    brand: "Samsung",
    rating: 4.7,
    status: "new",
    variant: "gadget",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "3",
    productName: "MacBook Air M3",
    slug: "macbook-air-m3",
    productImage: ["/image/products/product_3.jpg"],
    description: "Ultra-thin laptop with the powerful M3 chip and all-day battery life.",
    price: 1099,
    discount: 5,
    category: ["gadget", "laptop"],
    stock: 15,
    brand: "Apple",
    rating: 4.9,
    status: "new",
    variant: "gadget",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "4",
    productName: "Dell XPS 13",
    slug: "dell-xps-13",
    productImage: ["/image/products/Product_4.jpg"],
    description: "Premium Windows laptop with stunning InfinityEdge display.",
    price: 999,
    discount: 0,
    category: ["gadget", "laptop"],
    stock: 20,
    brand: "Dell",
    rating: 4.6,
    status: "sales",
    variant: "gadget",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "5",
    productName: "Sony WH-1000XM5 Headphones",
    slug: "sony-wh-1000xm5",
    productImage: ["/image/products/product_5.jpg"],
    description: "Industry-leading noise canceling headphones with exceptional sound quality.",
    price: 399,
    discount: 20,
    category: ["gadget", "audio"],
    stock: 40,
    brand: "Sony",
    rating: 4.8,
    status: "hot",
    variant: "gadget",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "6",
    productName: "iPad Pro 12.9-inch",
    slug: "ipad-pro-12-9-inch",
    productImage: ["/image/products/product_6.jpg"],
    description: "Professional iPad with M2 chip and stunning Liquid Retina XDR display.",
    price: 1099,
    discount: 0,
    category: ["tablet", "gadget"],
    stock: 18,
    brand: "Apple",
    rating: 4.7,
    status: "new",
    variant: "gadget",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "7",
    productName: "LG OLED C3 TV",
    slug: "lg-oled-c3-tv",
    productImage: ["/image/products/product_7.jpg"],
    description: "4K OLED TV with α9 Gen 6 AI Processor and stunning picture quality.",
    price: 1999,
    discount: 25,
    category: ["appliances", "tv"],
    stock: 8,
    brand: "LG",
    rating: 4.9,
    status: "hot",
    variant: "appliances",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "8",
    productName: "Samsung 65\" QLED TV",
    slug: "samsung-65-qled-tv",
    productImage: ["/image/products/product_8.jpg"],
    description: "Quantum Dot technology delivers over a billion shades of brilliant color.",
    price: 1499,
    discount: 15,
    category: ["appliances", "tv"],
    stock: 12,
    brand: "Samsung",
    rating: 4.6,
    status: "sales",
    variant: "appliances",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "9",
    productName: "Bose SoundLink Revolve+",
    slug: "bose-soundlink-revolve-plus",
    productImage: ["/image/products/product_9.avif"],
    description: "360° sound with deep, clear audio performance and 17-hour battery life.",
    price: 299,
    discount: 10,
    category: ["gadget", "audio"],
    stock: 35,
    brand: "Bose",
    rating: 4.5,
    status: "new",
    variant: "gadget",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "10",
    productName: "Dyson V15 Detect Vacuum",
    slug: "dyson-v15-detect-vacuum",
    productImage: ["/image/products/product_10.jpg"],
    description: "Laser dust detection and high torque cleaner head for deep cleaning.",
    price: 699,
    discount: 0,
    category: ["appliances", "cleaning"],
    stock: 10,
    brand: "Dyson",
    rating: 4.8,
    status: "hot",
    variant: "appliances",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "11",
    productName: "Ninja Foodi 10-in-1 XL Pro",
    slug: "ninja-foodi-10-in-1-xl-pro",
    productImage: ["/image/products/product_11.jpg"],
    description: "Air fry, pressure cook, slow cook, steam, bake, roast, dehydrate and more.",
    price: 249,
    discount: 30,
    category: ["kitchen-appliances", "cooking"],
    stock: 22,
    brand: "Ninja",
    rating: 4.4,
    status: "sales",
    variant: "appliances",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "12",
    productName: "Instant Pot Duo 7-in-1",
    slug: "instant-pot-duo-7-in-1",
    productImage: ["/image/products/product_12.jpg"],
    description: "Pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker.",
    price: 89,
    discount: 15,
    category: ["kitchen-appliances", "cooking"],
    stock: 50,
    brand: "Instant Pot",
    rating: 4.6,
    status: "hot",
    variant: "appliances",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "13",
    productName: "Keurig K-Classic Coffee Maker",
    slug: "keurig-k-classic-coffee-maker",
    productImage: ["/image/products/product_13.jpg"],
    description: "Brew delicious coffee in under a minute with K-Cup pods.",
    price: 79,
    discount: 20,
    category: ["kitchen-appliances", "coffee"],
    stock: 45,
    brand: "Keurig",
    rating: 4.3,
    status: "sales",
    variant: "appliances",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "14",
    productName: "KitchenAid Artisan Stand Mixer",
    slug: "kitchenaid-artisan-stand-mixer",
    productImage: ["/image/products/product_14.jpg"],
    description: "Professional-quality mixer with 10 speeds and 5-quart stainless steel bowl.",
    price: 379,
    discount: 10,
    category: ["kitchen-appliances", "mixing"],
    stock: 15,
    brand: "KitchenAid",
    rating: 4.9,
    status: "new",
    variant: "appliances",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "15",
    productName: "Nespresso VertuoPlus Coffee Maker",
    slug: "nespresso-vertuoplus-coffee-maker",
    productImage: ["/image/products/product_15.jpg"],
    description: "Centrifusion technology brews barista-quality coffee with rich crema.",
    price: 149,
    discount: 25,
    category: ["kitchen-appliances", "coffee"],
    stock: 30,
    brand: "Nespresso",
    rating: 4.5,
    status: "hot",
    variant: "appliances",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "16",
    productName: "Apple Watch Series 9",
    slug: "apple-watch-series-9",
    productImage: ["/image/products/product_16.jpg"],
    description: "The most advanced Apple Watch with double tap gesture and improved health features.",
    price: 399,
    discount: 0,
    category: ["gadget", "wearable"],
    stock: 28,
    brand: "Apple",
    rating: 4.7,
    status: "new",
    variant: "gadget",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "17",
    productName: "Fitbit Versa 4",
    slug: "fitbit-versa-4",
    productImage: ["/image/products/product_17.jpg"],
    description: "Advanced fitness tracker with built-in GPS and 6+ day battery life.",
    price: 199,
    discount: 15,
    category: ["gadget", "wearable"],
    stock: 35,
    brand: "Fitbit",
    rating: 4.4,
    status: "sales",
    variant: "gadget",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];